# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = FrmCaptureTool
QT += core gui widgets
include(FrmCaptureTool.pri)
