# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/utils/desktopfileparse.h \
    ./src/utils/desktopinfo.h \
    ./src/capture/screenshot.h \
    ./src/utils/confighandler.h \
    ./frmcapturetool.h \
    ./src/capture/widget/capturebutton.h \
    ./src/capture/widget/amplifierwidget.h \
    ./src/capture/widget/capturewidget.h \
    ./src/capture/widget/buttonhandler.h \
    ./src/capture/widget/qcolorpicker.h \
    ./src/capture/tools/undotool.h \
    ./src/capture/tools/toolfactory.h \
    ./src/capture/tools/sizeindicatortool.h \
    ./src/capture/tools/selectiontool.h \
    ./src/utils/screengrabber.h \
    ./src/capture/tools/savetool.h \
    ./src/capture/tools/rectangletool.h \
    ./src/capture/tools/penciltool.h \
    ./src/capture/workers/imgur/notificationwidget.h \
    ./src/capture/tools/movetool.h \
    ./src/capture/tools/markertool.h \
    ./src/capture/workers/imgur/loadspinner.h \
    ./src/capture/workers/imgur/imagelabel.h \
    ./src/capture/tools/exittool.h \
    ./src/capture/tools/copytool.h \
    ./src/capture/tools/circletool.h \
    ./src/capture/tools/capturetool.h \
    ./src/capture/capturemodification.h \
    ./src/capture/tools/blurtool.h \
    ./src/capture/tools/arrowtool.h \
    ./src/capture/tools/applauncher.h
SOURCES += ./frmcapturetool.cpp \
    ./main.cpp \
    ./src/capture/capturemodification.cpp \
    ./src/capture/screenshot.cpp \
    ./src/capture/tools/applauncher.cpp \
    ./src/capture/tools/arrowtool.cpp \
    ./src/capture/tools/blurtool.cpp \
    ./src/capture/tools/capturetool.cpp \
    ./src/capture/tools/circletool.cpp \
    ./src/capture/tools/copytool.cpp \
    ./src/capture/tools/exittool.cpp \
    ./src/capture/tools/markertool.cpp \
    ./src/capture/tools/movetool.cpp \
    ./src/capture/tools/penciltool.cpp \
    ./src/capture/tools/rectangletool.cpp \
    ./src/capture/tools/savetool.cpp \
    ./src/capture/tools/selectiontool.cpp \
    ./src/capture/tools/sizeindicatortool.cpp \
    ./src/capture/tools/toolfactory.cpp \
    ./src/capture/tools/undotool.cpp \
    ./src/capture/widget/amplifierwidget.cpp \
    ./src/capture/widget/buttonhandler.cpp \
    ./src/capture/widget/capturebutton.cpp \
    ./src/capture/widget/capturewidget.cpp \
    ./src/capture/widget/qcolorpicker.cpp \
    ./src/capture/workers/imgur/imagelabel.cpp \
    ./src/capture/workers/imgur/loadspinner.cpp \
    ./src/capture/workers/imgur/notificationwidget.cpp \
    ./src/utils/confighandler.cpp \
    ./src/utils/desktopfileparse.cpp \
    ./src/utils/desktopinfo.cpp \
    ./src/utils/screengrabber.cpp
FORMS += ./frmcapturetool.ui \
    ./src/capture/widget/amplifierwidget.ui \
    ./src/capture/widget/qcolorpicker.ui
RESOURCES += frmcapturetool.qrc
